### ISSUE TITLE
Service Support

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2-module-cube#13]
Hello,
The cube module is already great to quickly produce dashboards ! 
But currently, it can only deal with host statistics. Is it planned to support the service statistics?
Regards,
Yannick

**Comment by cbnorman** [comment]
+1 this would be great for us too

**Comment by Zappo-II** [comment]
+1
Count me in:
* Would like to see subtiles with sum of service states grouped by severity ([ok], warning, critical, unknown)
* Would like to see additional "Show Service Status" panel on "...cube/index/details"

**Comment by yaomacbt** [comment]
Really would like to make cube can count services status also.

**Comment by nilmerg** [comment]
Hey all,

well... we're having four topics here:

a) Service based cubes (as the OP requests)
b) Service state counters
c) Service states as dimension
d) Slice colors based not only on host states but also/instead on service states

I consider this issue primarily being about a).

For b) and c) please create separate issues if interested.

For d), please head over to the business process module. There you can even choose how multiple states are combined. (e.g. and, or, not, ...)
