### ISSUE TITLE
Cube module does not work if icingadb-web is disabled or missing

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2-module-cube#131]
## Describe the bug

Trait 'Icinga\Module\Icingadb\Common\Auth' not found

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

## To Reproduce
1. disable icingadb module
2. Reporting->Cube
3. add Dimension
4. throws exception

<img width="656" alt="2023-04-03 18_11_05-Cube_ __ Icinga Web" src="https://user-images.githubusercontent.com/29682206/229568183-bd6e4fb4-e96f-4bce-b229-659a490b0536.png">

## Your Environment

Include as many relevant details about the environment you experienced the problem in
* Cube 1.3
* Icinga Web 2 version and modules (System - About): 2.11.4
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.13.7
* PHP version used (`php --version`): 7.4
* Server operating system and version:
Ubuntu 20.04

**Comment by nilmerg** [comment]
Ouch, thanks for reporting!

**Comment by Tqnsls** [comment]
pull works for me.
