### ISSUE TITLE
Cube (ido) does not work in Dashboards anymore

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2-module-cube#135]
## Describe the bug

The Cube module throws an exception 'Got no such dimension: "showCompact"' when added to a dashboard
<img width="299" alt="2023-05-10 19_28_25-Current Incidents __ Dashboard __ Icinga Web" src="https://github.com/Icinga/icingaweb2-module-cube/assets/29682206/32be3d4c-7031-4377-bd1a-7055df7c6081">

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.4
* Cube 1.3

**Comment by tbauriedel** [comment]
ref/NC/786778
