### ISSUE TITLE
Allow array and dictionary custom vars

### ISSUE THREAD

**Issue by ClemensBW** [Icinga/icingaweb2-module-cube#15]
Hello,

can you please add a option to search in array of cust.vars?
Looks very useful for comparison in the cube :)

**Comment by Zappo-II** [comment]
I have the impression that any Array configuration like this one...
```
object Host "Director-Test-Host" {
    import "default-host-template"
    address = "127.0.0.1"
    vars.my_value_array = [ "DeathStarPlans", "NotTheDroids" ]
}
```
...won't make it into the `+ Add a dimension` drop down list at all.

If that is intended behaviour, then please consider this a feature request, otherwise this might be some kind of bug...

**Comment by dnsmichi** [comment]
Icinga Web 2 only has a JSON column available, that follows the request in Icinga Web 2 to use such for the filter editor. Unless there's some decision in Web 2 how to handle such, this feature request is more or less stalled.

**Comment by mtdeguzis** [comment]
Not sure if this would be a new request or not, but I feel the display of arrays for cubes is messy, or am I not doing this right? Cube dimensions with arrays just show test such as `['value1','value2']`. With a strict square shape, these are hard to see if I assign more than 2 objects to an array.

**Comment by nilmerg** [comment]
With Icinga DB Web this is now possible. Works for array type variables fine as well with the latest release.
