### ISSUE TITLE
Allow to filter slices

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-cube#16]
Featurerequest Icinga2 Filters on Cube Slices

**Comment by Thomas-Gelf** [comment]
Any chance you could provide a detailed description of what you want to see implemented?

Cheers,
Thomas

**Comment by Wintermute2k6** [comment]
I think it would provide additional benefits if you could use the standard filtering from Icinga Web 2 in the Cube module as well on each of the slices. 
Not only in the slices cubes itself but from a global filter like in the screenshots above the each of the cubes.

![pastedimage](https://cloud.githubusercontent.com/assets/7203835/24693629/c86eaa10-19de-11e7-89f6-1933144d92ad.png)

![pastedimage1](https://cloud.githubusercontent.com/assets/7203835/24693635/ceb6e144-19de-11e7-8e28-bef6a8a5cae3.png)

**Comment by Thomas-Gelf** [comment]
Got it, makes sense to me!
