### ISSUE TITLE
Cannot add any "Cube" dimension

### ISSUE THREAD

**Issue by Animancorda** [Icinga/icingaweb2-module-cube#26]
Hello community, need some help

I met a problem (or not) - cannot add any "Cube" dimension, by clicking on "+ add a dimension" nothing happened.

**System:**
- Debian 9

**Server:** 
- Icinga "r2.6.0-1"
- Icinga Web "2.5.1"

**Modules:**
- Cube "1.0.1"
- Director "master" (what's wrong with this version O_o)
- Monitoring "2.5.1"
- Migrate "2.5.1"

**Other:** 
- Apache "2.4.25"
- PHP "7.0.27"

**Comment by dnsmichi** [comment]
Can you share a screenshot what you mean exactly?

**Comment by Animancorda** [comment]
Here is it:
![shot](https://user-images.githubusercontent.com/38096921/38602185-b2177e82-3d72-11e8-9201-034ecc2e68b5.png)

**Comment by Animancorda** [comment]
lippserd, yes i have

**Comment by dnsmichi** [comment]
Custom atttributes/vars are configured in Icinga 2 itself, or you'll go with the mentioned Director examples in the docs. Not sure what to add to the docs here, can you propose something?

**Comment by Animancorda** [comment]
dnsmichi, thanks for your support and responsiveness

Would be glad to see the section "custom variables" in docs. Section filled with examples of situations in which Icinga 2 allows you to create variable.

For example - creating new field in Director and adding it to host template allow you to create variable named as that field. So you can easly add this variable as new dimension to Cube. String values added to that field will be displayed as cubes. 

Also have one more question. I created custom field named "location" and attached to it new list with some settlements. After that i attached this field to host template, so i can choose in hosts their instalation place. So the question - how can i make Cube to show me variable lable? Currently i see only variable name. Same with list - Cube shows me variable name of list entry, not it label.

**Comment by nilmerg** [comment]
I guess this is solved. Closed.
