### ISSUE TITLE
Enhance display of long facts

### ISSUE THREAD

**Issue by kevinstiller** [Icinga/icingaweb2-module-cube#30]
Add the possibility to show cubes as a normal treeview and makes this setting global to all users.

Background: We have some long Strings and the cubes aren't readable at all. ;-)

PS: Nice work!

**Comment by nilmerg** [comment]
Hi,

thank you for the suggestion. Though, if we'd add such a thing like a tree view (i.e. not a cube) the module would also need a new name.

What I actually mean of course is that this doesn't really match this module's intent. So no, a tree view is not what this module will provide. (Take a look at the business process module if you want such a thing)

Long values however should be displayed correct. If that's not the case or looks weird it needs to be fixed.

**Comment by widhalmt** [comment]
ref/NC/611533
