### ISSUE TITLE
More than three dimensions won't work

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2-module-cube#31]
Adding more than three dimensions causes the inner tiles to overflow.

## Expected Behavior
It should either not be possible to add more than three dimensions or should be properly handled.

## Current Behavior
Adding a fourth dimension splits the inner tiles and each further dimension also splits the tiles further. Any fourth dimension already causes the tiles to overflow.

## Possible Solution
Don't allow to add more than three dimensions. Maybe use remaining facts to "drill down".

## Your Environment
* Module version (System - About): master
* Icinga Web 2 version and modules (System - About): master

**Comment by theFeu** [comment]
I would advise against more than 3 dimensions for now as well.

I think that we could always extend it if someone needs it (in a later version) but would limit it to three for now :)
