### ISSUE TITLE
Error in SQL syntax if custom var names contain dots

### ISSUE THREAD

**Issue by u10t010** [Icinga/icingaweb2-module-cube#45]
## Describe the bug
- In Icingaweb2/Cube selecting in "Add a dimesion"  for example "os.version" the following error occurs

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`version`, rollup.`hosts_cnt`, rollup.`hosts_nok`, rollup.`hosts_unhandled_nok`' at line 1, query was: SELECT rollup.`os`.`version` AS `os`.`version`.........

- Selecting a dimesion like "check_command" everything is fine

## To Reproduce
1. select a dimension including a dot "." the error occurs
2. select a dimension without a dot (e.g. "check_command") everything is fine

## Expected behavior
A dimension including a dot "." should also be possible

## Your Environment
* Verion and modules (System - About):
    Icinga version: r2.10.5-1 
    Icinga Web 2 Version 2.7.1
    cube  module version  1.1.0 
    OS: Debian 10 (buster)
    mariadb 10.3.15-1
    PHP 7.3.4-2

## Additional context
Thank you in advance for your kind help

**Comment by nilmerg** [comment]
Hi, thanks for the report.

I thought this is fixed since #38, are you sure you've installed v1.1.0 of the cube module?

**Comment by u10t010** [comment]
Hello Johannes,

thank you for your reply.

Yes, i'm sure we've installed v1.1.0 of the cube module

root@........# icingacli module list
MODULE         VERSION   STATE     DESCRIPTION
cube           1.1.0     enabled   Cube for Icinga Web 2

Maybe the problem is the dot "." in our dimension-list like 
"cluster.name" or "os.version" etc. ?

kind regards
u10t010
