### ISSUE TITLE
Cube do not turn yellow for Warning

### ISSUE THREAD

**Issue by radioactive9** [Icinga/icingaweb2-module-cube#47]
Cube is working as expected and is most sought for feature to provide / build necessary dashboard. Only challenge we see is if there is a Warning alert within the cube and no other - it still turns red / as if critical. This sometimes is confusing for command centers to decide the priority on which they should work. If Cube can pick up the Warning and display accordingly it will be great - like in Business Process module

**Comment by nilmerg** [comment]
Hi, thanks for the report!

Reproduced it successfully, a fix will follow.

**Comment by radioactive9** [comment]
Hello

Do we have any beta for testing ?
