### ISSUE TITLE
Missing context in the cube title tooltip

### ISSUE THREAD

**Issue by stebr1** [Icinga/icingaweb2-module-cube#52]
On medium/long Object name string, it is truncated after some characters.
Please consider to create an hint on hover that will help the users to read the complete name of the object.
Actually the hint on hover is "Show more details"

It is confiured at line 300 of this file "library/Cube/CubeRenderer.php"

`           . '" title="' . $view->escape('Show more details') . '"'
`
![cube-hint](https://user-images.githubusercontent.com/1777975/77157130-0d154c80-6aa1-11ea-826f-1f985730231e.png)

**Comment by lippserd** [comment]
Makes sense. Thanks for the report!

**Comment by stebr1** [comment]
Hi @lippserd I confirm that the patch work fine

**Comment by lippserd** [comment]
Thanks for the feedback.
