### ISSUE TITLE
Sort the dimension list alphabetically

### ISSUE THREAD

**Issue by stebr1** [Icinga/icingaweb2-module-cube#53]
Actually the sorting of the list dimension is not sorted in a useful way
Could be very useful to have an alphabetically sorting of the dropdown menu, because it is very difficult to search some string when the number of this strings are > 100

![image](https://user-images.githubusercontent.com/1777975/77158228-29b28400-6aa3-11ea-8dfb-9d8300009168.png)

**Comment by lippserd** [comment]
Again, thanks for the report.

**Comment by nbuchwitz** [comment]
Hi @stebr1 

Which version of the module do you use? I tested against the latest release (v1.1.0) and get a correctly sorted list (on PostgreSQL and MySQL)

**Comment by lippserd** [comment]
@stebr1 Could you please test the related PR and provide feedback?
