### ISSUE TITLE
Data fields / custom vars do not show up or take a long time to do so 

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2-module-cube#57]
## Describe the bug
It seems some of my data fields do not show up under services/hosts within Reporting > Cube (more often it's a service). I tried to see if any errors were thrown in icinga2.log or icingweb2.log and the Chrome browser console.

Is this a matter of propagation? I’ve seen this too when I delete a data field called “applications” (yes, confirming to delete dependent host assignments), and adding them, they never show up.

NOTE: This seems to apply to arrays, as my data list of string type shows up fine:
![image](https://user-images.githubusercontent.com/27829577/77665797-822bca80-6f56-11ea-886e-b29fed40fdfa.png)

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Add data filed called "service_group" of type Array
2. Add a few services to this array on any service apply/assignment rule.
3. Deploy any changes if needed with Director
4. Go to Cube and try to access this array.

## Expected behavior
The array var should show up.

## Screenshots

![image](https://user-images.githubusercontent.com/27829577/77665997-c7e89300-6f56-11ea-8332-cff228ef76eb.png)
![image](https://user-images.githubusercontent.com/27829577/77666029-d040ce00-6f56-11ea-8ce7-0f0a095cae9e.png)
![image](https://user-images.githubusercontent.com/27829577/77666152-f5354100-6f56-11ea-9b3b-f4e36c3507b3.png)
![image](https://user-images.githubusercontent.com/27829577/77666167-f9f9f500-6f56-11ea-8d2e-aaca63d723cc.png)
![image](https://user-images.githubusercontent.com/27829577/77666183-00886c80-6f57-11ea-84f4-6fcb5bd4d390.png)

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):  Icinga Web 2 Version 2.7.3, Git commit 06cabfe8ba28cf545a42c92f25484383191a4e51
* Web browser used: Chrome 80.0.3987.122
* Icinga 2 version used (`icinga2 --version`): 2.11.3-1
* PHP version used (`php --version`): 
```
# /opt/rh/rh-php71/root/usr/sbin/php-fpm --version
PHP 7.1.30 (fpm-fcgi) (built: Nov  4 2019 10:09:22)
```
* Server operating system and version: CentOS 7.7

## Additional context
* https://community.icinga.com/t/icinga-cube-module-data-fields-do-not-show-up-or-take-a-long-time-to-do-so/3893
* https://community.icinga.com/t/cube-add-dimension-issue/2085

**Comment by lippserd** [comment]
Hi,

Thanks for the detailed report but we really do not support dicts or arrays as custom var values.
That will change once we've implemented support for the Icinga DB as backend here.

You've already commented to #15 which is pretty much the same issue.

All the best,
Eric

**Comment by Mikesch-mp** [comment]
@lipserd so many users that dont want to use IcingaDB are left behind? i think as long both monitoring modules are supported all "official" modules should work with same feature set.

**Comment by lippserd** [comment]
Schema issues especially with custom vars were one of the reasons to introduce Icinga DB.
Icinga DB is where we move on. IDO will be deprecated once we've released the final version.
I'm afraid but maintaining the same feature set can't and won't happen.

**Comment by Mikesch-mp** [comment]
Now iam complete confused, differs a lot from what was told on Camps/OSMC

**Comment by lippserd** [comment]
I don't know what your problem is, but please send a mail instead of spamming just some words to the **issue** tracker.

A mannered response would include at least a why you're confused because really what should I answer to that?
