### ISSUE TITLE
Host variables in service dimension list

### ISSUE THREAD

**Issue by manny4566** [Icinga/icingaweb2-module-cube#90]
Problem:

We have a data field in string format.
This data filed is passed to a host template and thus mapped to each host as a variable. 
There it is filled with different values
Furthermore we have a check command, which reads this host variable and passes it as argument to the check.

Cube does not show this variable under services for selection.
Furthermore it is hard to understand when a variable is displayed under services. Which requirements must be fulfilled ?
Please make it more transparent to understand how this dimension list is created and when new values end up in it or a way to populate it yourself. 
Thanks

**Comment by lippserd** [comment]
Hi,

Only the direct custom variables of the services are listed there.

All the best,
Eric
