### ISSUE TITLE
Host cubes displays number of services instead of number of hosts

### ISSUE THREAD

**Issue by tfylling** [Icinga/icingaweb2-module-cube#98]
## Describe the bug

When I create a host cube and select a host variable, the slices show the number of services on the matching hosts instead of the number of hosts. This also takes a lot more time than it ought to if it was just iterating over the hosts. Also just loading the `Hosts`-tab in the Cube page takes quite a while. Clicking the name of the slice give a host list with just the relevant host as expected.
It seems to me that both in showing the cube and in fetching the dimension options for a cube it iterates over the service objects, using their host variables, rather than the host objects, but this is just conjecture.

## To Reproduce

1. Create a new cube
2. Select the Hosts tab
3. Add a dimension, custom variable or otherwise
4. Observe that the slices show numbers of services who's host match the criteria

## Expected behavior

The slices should show the number of hosts matching the criteria. For example the Darwin slice in the screenshot below should show 6, not 116, which is the total number of services on those six hosts.

## Screenshots

![image](https://user-images.githubusercontent.com/20243684/205273595-9583479a-ba94-4708-bb35-3e137c9832c0.png)

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.2
* Web browser used: Vivaldi, Chrome & Firefox
* Icinga 2 version used (`icinga2 --version`): r2.13.6-1
* PHP version used (`php --version`): 8.1.2-1ubuntu2.8
* Server operating system and version: Ubuntu 22.04.1

**Comment by nilmerg** [comment]
Since you didn't include which cube version you have, make sure to install the latest and report back.

**Comment by tfylling** [comment]
Sorry, yes. It wasn't a part of the bug template, so I forgot to include it. cube version is 1.2.2, which is the latest version as far as I understand.

**Comment by nilmerg** [comment]
Is this a PostgreSQL database backend by chance?

**Comment by tfylling** [comment]
It is, yes.

**Comment by nilmerg** [comment]
Confirmed. Though, I had to configure a restriction first (Using `servicegroup_name`)

**Comment by nilmerg** [comment]
I'm afraid, but I cannot reproduce it anymore. I'm sure I was able to, but I tried every possible combination of:

* User A in Role B restricted to a service group in which every service of any host is
* User B in Role A restricted to a service group in which at least one service of any host is
* User C in Role C restricted to two servicegroups in which some services are in the first and all in the second

None showed the described issue. Please wait for the next release, try it again and report back.

**Comment by tfylling** [comment]
I think this may now have resolved itself. I wish I could be certain, but after an update of icinga shortly after the cubemodule now just says.
```
Trait "Icinga\Module\Icingadb\Common\Auth" not found

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main
```
I've not found much relevant help on this from google, so I should probably create a separate issue for this, unless it's a known easy fix.
